INSERT INTO GARE (ID_GARE, NOM_GARE, REGION_GARE, CODE_REGION_GARE, DEPARTEMENT_GARE, CODE_DEPARTEMENT_GARE, VILLE_GARE ,CODE_VILLE_GARE )
VALUES (249, 'Laluque', 'Nouvelle-Aquitaine', 75, 'LANDES', 40, 'LALUQUE', 40465);
